### PR TITLE
upgrade dependencies

### PR DESCRIPTION
**Pull request by pjfanning**
Trying to make it easier to support scala 2.13.0 release

### CODE REVIEW

**Comment by tarao** [comment]
Thanks!

**Comment by pjfanning** [comment]
Thanks @tarao I've been trying out using Cats NonEmptyList instead of your NonEmpty implementation (because Cats has a scala 2.13 release). Do you plan to release a scala 2.13 jar for nonempty? This might be awkward because scala collections changed quite a lot (CanBuildFrom has been removed in factory of Factory). Or would you consider using the Cats NonEmptyList instead?

**Comment by tarao** [comment]
I'm planning 2.13-adapted release of nonempty.  I know the changes in the standard Scala collections.  It shouldn't be so difficult if I re-implement `NonEmpty` with Scala 2.13 collections.  The problem is cross-building but maybe I should leave the old source in a separate branch.

I know few about Cats' NonEmptyList.  If it is possible to convert a standard `List`-like thing to Cats' NonEmptyList (actually it must be `Option[NonEmptyList]` in case it is empty) in O(1), I should consider using it here.  Otherwise, I will keep updating my `NonEmpty`.

I was wondering if I should use something like `Iterable[A] Refined NonEmpty` by using [refined](https://github.com/fthomas/refined).  I prefer this way if it matches our usage.  Maybe you can give it a try.

**Comment by pjfanning** [comment]
if you add a dependency on scala-collection-compat lib, you can write code that is 2.13 friendly but that will also work in older versions of scala.

**Comment by tarao** [comment]
I know it too but I'm not sure if it can live with `CanBuildFrom` hacks.

**Pull request merged**
